services:
  php:
    container_name: pet-laravel-php
    build:
      context: .
      dockerfile: php.Dockerfile
    volumes:
      - .:/var/www
    working_dir: /var/www
    user: 1000:1000
    environment:
      PHP_IDE_CONFIG: "serverName=laravel"
    depends_on:
      - db
    networks:
      - laravel

  nginx:
    container_name: pet-laravel-nginx
    image: nginx:1.27
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8080:80"
    depends_on:
      - php
    networks:
      - laravel

  db:
    container_name: pet-laravel-mysql
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel

volumes:
  mysql_data:

networks:
  laravel:
    driver: bridge